### ISSUE TITLE
Output messages can get out of order near module switching

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#12]
When watching the output window, I notice that the messages appear out of order when the application  changes from module to module.

**Comment by chrispadgett** [comment]
this seems to be mostly fixed with issue#15, only 1 message near the end has an issue

**Comment by paulwrodriguez** [comment]
I ran the program a few times and don't see this anymore. take a screenshot the next time you see this so I can track down the issue. I saw it happening last week. 

the program runs much slower now so maybe an out of order thing will be harder to find but in case it does.
