### ISSUE TITLE
Mesh is not being created

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#13]
Currently, the mesh is not being created on my Netbook
![error](https://cloud.githubusercontent.com/assets/3378627/12668085/736cd3b6-c610-11e5-9131-6782fecfe1e1.png)

**Comment by paulwrodriguez** [comment]
it is not created on my machine as well.

**Comment by paulwrodriguez** [comment]
im a liar. just tried it again and it created a mesh. It doesnt work with mr.oni. Works with the others for me. Also, @chrispadgett the component gets stucks somewhere on ur end. I made a branch if you want to check it out when you get a chance.

**Comment by chrispadgett** [comment]
I'm testing it now, come hang out in slack

**Comment by chrispadgett** [comment]
I'm still not getting a mesh created when using the test file "straightThruHall.oni".
![issue 13](https://cloud.githubusercontent.com/assets/3378627/12698873/e3bb47be-c765-11e5-9c7b-8dcd73724fd7.png)

Attaching log file.
[output.txt](https://github.com/ProjectIRoniC/OpenPointMesh/files/111033/output.txt)

**Comment by paulwrodriguez** [comment]
not sure if it has been said but the k tree thing is probably one of mat's components not liking the stitched file. Just a guess.

**Comment by paulwrodriguez** [comment]
> /home/paul/Documents/res/overlappingParallelC1of2C.oni selected
> /home/paul/Documents/res/pcdfiles selected for output
> calling onitopcd
> Start oni data output...
> Output to /home/paul/Documents/res/pcdfiles
> before loop
> in loop
> Working on file /home/paul/Documents/res/overlappingParallelC1of2C.oni
> File open success...
> Frames to read 22...
> Processing 640x480 frame number 25...
> Processing 640x480 frame number 50...
> Processing 640x480 frame number 75...
> Processing 640x480 frame number 100...
> Processing 640x480 frame number 125...
> Processing 640x480 frame number 150...
> Processing 640x480 frame number 175...
> Processing 640x480 frame number 200...
> Processing 640x480 frame number 225...
> Processing 640x480 frame number 250...
> Processing 640x480 frame number 275...
> Processing 640x480 frame number 300...
> Processing 640x480 frame number 325...
> Processing 640x480 frame number 350...
> Processing 640x480 frame number 375...
> Processing 640x480 frame number 400...
> Processing 640x480 frame number 425...
> Processing 640x480 frame number 450...
> Processing 640x480 frame number 475...
> Processing 640x480 frame number 500...
> Processing 640x480 frame number 525...
> Processing 640x480 frame number 550...
> Last frame has been read...
> after loop
> calling cloudsticher
> Start point cloud stitching...
> Working on stitching /home/paul/Documents/res/overlappingParallelC1of2C.oni...
> Output final point cloud to /home/paul/Documents/res/pcdfiles/overlappingParallelC1of2C.oni_finalPointCloud.pcd
> Read in 22 files.
> Spinning up 1 threads.
> processing 22 frames.
> Loaded 22 datasets
> total point count: 134
> registered cloud 1/22
> total point count: 173
> registered cloud 2/22
> total point count: 187
> registered cloud 3/22
> total point count: 239
> registered cloud 4/22
> total point count: 281
> registered cloud 5/22
> total point count: 287
> registered cloud 6/22
> total point count: 291
> registered cloud 7/22
> total point count: 305
> registered cloud 8/22
> total point count: 315
> registered cloud 9/22
> total point count: 325
> registered cloud 10/22
> total point count: 330
> registered cloud 11/22
> total point count: 336
> registered cloud 12/22
> total point count: 342
> registered cloud 13/22
> total point count: 345
> registered cloud 14/22
> total point count: 346
> registered cloud 15/22
> total point count: 347
> registered cloud 16/22
> total point count: 348
> registered cloud 17/22
> total point count: 367
> registered cloud 18/22
> total point count: 372
> registered cloud 19/22
> total point count: 391
> registered cloud 20/22
> total point count: 395
> registered cloud 21/22
> Successfully outputted stitched pcd file to: /home/paul/Documents/res/pcdfiles/overlappingParallelC1of2C.oni_finalPointCloud.pcd
> Successfully outputed ply file to: /home/paul/Documents/res/pcdfiles/overlappingParallelC1of2C.oni_finalPointCloud.ply
> calling Meshcons
> Start mesh constructor...
> File used for construction /home/paul/Documents/res/pcdfiles/overlappingParallelC1of2C.oni_finalPointCloud.pcd
> Output final mesh to /home/paul/Documents/res/pcdfiles/finished_mesh.ply
> Original Cloud Size: 395
> New Cloud Size: 214
> Removed 181 points.
> Radius Removal Cloud Size: 0
> Removed 214 points.
> Finished mesh reconstruction.
> Mesh contains 0 polygons.
> Saved new polygon mesh to: /home/paul/Documents/res/pcdfiles/finished_mesh.plyMesh constructor complete.

this is what i get when i run a file. its clearly the mesh part that doesnt like something. when the program goes to that point i get the tree error.

**Comment by chrispadgett** [comment]
I think this is fixed with commit https://github.com/ProjectIRoniC/OpenPointMesh/commit/1d39f1ba3da3c27067cb691f961406a020f5a814 The field of view was being incorrectly grabbed.

**Comment by chrispadgett** [comment]
Merged fix to master https://github.com/ProjectIRoniC/OpenPointMesh/commit/f5839747b774ca1b73d04d0a29ef889cb257e131
