### ISSUE TITLE
GTK_IS_WIDGET failed

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#14]
Need to revisit this error. While it doesn't seem to affect functionality at the moment, it might come back to bite us later.
![error](https://cloud.githubusercontent.com/assets/3378627/12668180/275bdbec-c611-11e5-9b68-3e22bcdf8d3a.png)

**Comment by paulwrodriguez** [comment]
whenever someone else gets the chance test the fix. if solved then ill close the issue.

**Comment by chrispadgett** [comment]
I still see this issue in branch iss13
![issue 14](https://cloud.githubusercontent.com/assets/3378627/12698830/d6d5b1f2-c764-11e5-837a-64eaa32b677d.png)

It occurs immediately upon application launch

**Comment by paulwrodriguez** [comment]
thats so odd. I dont have that.

**Comment by paulwrodriguez** [comment]
from my research it looks like this could be a plateform issue. some people report this type of error. since I dont have it, it makes me thing its the way ur machine is built compared to mine.
