### ISSUE TITLE
Cannot queue arguments of type QTextBlock and QTextCursor

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#15]
This has something to do with the gui not supporting being reentrant.
![error](https://cloud.githubusercontent.com/assets/3378627/12668172/1db61440-c611-11e5-9880-0c07d6b58eec.png)

**Comment by paulwrodriguez** [comment]
what were you trying to do?

**Comment by chrispadgett** [comment]
Steps to Reproduce:
1. ./vba in terminal
2. Select Start button
3. Observe terminal output

I don't think I changed any of the code related to the connections

**Comment by paulwrodriguez** [comment]
yea thats odd. I just checked the old version and that did not occur but Ill look into what changed. should help find the issue faster.

**Comment by paulwrodriguez** [comment]
I should have put a comment on the function you used but you changed all the output statements and added a few in the incorrect way. The way I have it setup, you need to either use the output buffer or emit signals. Signals get added to a separate queue and can be processes async. I will correct the issue.

**Comment by chrispadgett** [comment]
So the problem is related to the use of "appendMessage()"? I wasn't sure if
all of the messages should be appendMessage or outputBuffer->push()
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by paulwrodriguez** [comment]
correct. The way I used appendmessage before was to force something to be written immediately to the details console. Basically if they tried to click start before choosing a file or something since there might be a small delay on the buffer output. My thought process was that it was poor ux to have the user click start and only after a pause would see the error message come up. So i hacked it :) 

before you couldnt use it after the start of all the threads for this access reason. It 'works' now technically but you get that error/warning message.

**Comment by chrispadgett** [comment]
Ok info noted, I will use outputBuffer->push() from now on.
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by paulwrodriguez** [comment]
actually i was going to just change the function to be used in this way. so you keep using it. With the shorter wait time you added maybe it wont be so awkward. either way ill make a function for it. dont just access the buffer. It will help when we add error handling later. probably a different buffer. or a user defined object inside buffer. not decided.
