### ISSUE TITLE
UI Title Bar needs updating

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#17]
The UI Title Bar should be updated to the new project name "Open Point Mesh"

Also it says "Volcano Bot", which we should probably remove.

![uiupdate](https://cloud.githubusercontent.com/assets/3378627/12699815/5df16920-c787-11e5-8623-f37ddf15422e.png)

**Comment by paulwrodriguez** [comment]
I believe this is removed. can someone check title-bar branch. i never actually saw it on my gui. but I did find a field that was holding this value.

**Comment by paulwrodriguez** [comment]
fixed with commit  3e2fdf0
