### ISSUE TITLE
Includes using "../build/ui_*.h" causes build issues if the user does not have their build directory as "build"

### ISSUE THREAD

**Issue by chrispadgett** [ProjectIRoniC/OpenPointMesh#54]
In the files:
- AboutDialog.cpp
- AccuracyControlMenu.h
- mainwindow.cpp

There are includes that follow the form: `#include "../build/ui_*.h"` which causes build problems when the user does not have have their build in a folder _<repo_root>/build_ An example might be they have their build in a folder called _<repo_root>/OPM_SuperBuild_

We need to find a way to change the path of this include so we can avoid this issue. Maybe we can make the generated files put into a static directory like _<repo root>/ui_generated_.

**Comment by paulwrodriguez** [comment]
techinically we can manually create these files and put them in a sub dir somewhere. we would need to add a note in the build process for the next team though. Eventually we (or the next team) would need to add a command to cmakelist that creates these files as apart of the build process.

**Comment by chrispadgett** [comment]
Fixed with commit 64c274bda4e04c71e884f9c7a77b6abf38c63dd9
